### PR TITLE
Resource detail layout

### PR DESCRIPTION
**Pull request by FarajiA**
## JIRA:
See ticket here - https://jira.rax.io/browse/MNRVA-339

 ## Description:
Add Resource detail layout + placeholders for Monitors & Suppressions. To note a lot of the language around this feature is still TBD I'm having trouble getting a finalized version of verbiage from leadership. 

 ## Testing:

 ## Screenshots:
resourceDetail

### CODE REVIEW

**Comment by itzg** [comment]
Commenting on the screenshot first:

- resource ID probably shouldn't be displayed since it's a DB ID
- not sure if "Monitoring Agent" and "Agent ID" should be shown
- rather than "IP addresses" I'd prefer you generically list out the metadata
- similarly this view is missing the labels of the resource
- perhaps leave off "Product Type" until requirements are clearer

**Comment by FarajiA** [comment]
- [x] resource ID probably shouldn't be displayed since it's a DB ID
 - [ ] not sure if "Monitoring Agent" and "Agent ID" should be shown
    - Agent ID removed, there is a field for monitoring agent presence, maybe this works for yes or no?
       https://github.com/racker/Minerva/blob/master/src/app/_mocks/resources/single.json#L15
- [x] rather than "IP addresses" I'd prefer you generically list out the metadata
 - [ ] similarly this view is missing the labels of the resource
   - This may still have to be addressed I'm having trouble getting direction from product management on       this item so I can attempt to display in some way and if management sees an issue I can update.
 - [x] perhaps leave off "Product Type" until requirements are clearer

**Comment by itzg** [comment]
> * [ ]  not sure if "Monitoring Agent" and "Agent ID" should be shown
>   
>   * Agent ID removed, there is a field for monitoring agent presence, maybe this works for yes or no?
>     https://github.com/racker/Minerva/blob/master/src/app/_mocks/resources/single.json#L15

That particular field is useful to show, but a new field has just been added, `associatedWithEnvoy`, which relates better to what used to be an agent ID on the entity.

**Comment by FarajiA** [comment]
Latest:

latestDetailPage

**Comment by FarajiA** [comment]
Latest: 

latestDetailPage

**Comment by FarajiA** [comment]
Latest updates addresses:

> * [ ]  not sure if "Monitoring Agent" and "Agent ID" should be shown
>   
>   * Agent ID removed, there is a field for monitoring agent presence, maybe this works for yes or no?
>     https://github.com/racker/Minerva/blob/master/src/app/_mocks/resources/single.json#L15

> * [ ]  similarly this view is missing the labels of the resource
>   
>   * This may still have to be addressed I'm having trouble getting direction from product management on       this item so I can attempt to display in some way and if management sees an issue I can update.

latestDetailPage

**Comment by itzg** [comment]
@FarajiA sorry, I kept meaning to grab the latest resource response example and then kept getting distracted. Here is an example from the latest call to `GET /api/resources`

```json
{
  "content": [
    {
      "tenantId": "aaaaaa",
      "resourceId": "development:0",
      "labels": {
        "agent_discovered_arch": "amd64",
        "agent_discovered_hostname": "MS90HCG8WL",
        "agent_environment": "localdev",
        "agent_discovered_os": "darwin"
      },
      "metadata": null,
      "presenceMonitoringEnabled": true,
      "region": null,
      "associatedWithEnvoy": true,
      "createdTimestamp": "2019-06-06T15:44:11Z",
      "updatedTimestamp": "2019-06-06T15:44:11Z"
    }
  ],
  "number": 0,
  "totalPages": 1,
  "totalElements": 1,
  "last": true,
  "first": true
}
```

From that, I would recommend using `associatedWithEnvoy` as the general indication of "Monitoring agent: yes", but leave off a specific agent ID for now.

**Comment by FarajiA** [comment]
Here's the latest, I'm now using the `associatedWithEnvoy` field for Monitoring Agent and removed agent ID. I've also updated the `single.json` mock per specification.

latestDetailPage

**Pull request merged**
