### PR TITLE
Monitor details page

### PR DESCRIPTION
**Pull request by FarajiA**
## JIRA:
See ticket here - https://jira.rax.io/browse/MNRVA-348

 ## Description:
Monitor details page - more attention is needed to this markup to accommodate _all_ monitor types. Fields not shown here below labels will need to be dynamically loaded depending on the type of monitor.
 
 ## Testing:
`npm run test`

 ## Screenshots:
monitorDetails

### CODE REVIEW

**Comment by itzg** [comment]
FYI this gets into another realm of terminology I hadn't even covered yet :) In Salus, they will be "Event Tasks" since the industry tends to distinguish events from alert/alarms and at the "lower level" Salus is producing events. Like the label-selection decoupling of monitors from resources, event tasks are also decoupled from the resource/monitor that originated the data. Event tasks address the data to analyze by tenant, measurement name, and labels.

So...the traditional/v1 listing of alarms per check doesn't exist in v2.

While you're at it, I'd say leave out the suppressions aspect until the business groups decide who/how suppressions and notifications will be properly done.

**Comment by FarajiA** [comment]
Okay noted. In that case we can probably show events associated with the labels present in that Monitor.

I'm also wondering is the Monitor has the ability to be deactivated i.e. a status field and whether there's any field or an association that can identify the type of monitor?

**Comment by itzg** [comment]
We don't yet have a way (or plan) to deactivate a monitor. As for the type of monitor, the monitor CRUD operations include a `type` as part of the body, such as `cpu` and currently line up with a subset of these https://github.com/influxdata/telegraf/tree/master/plugins/inputs

**Comment by itzg** [comment]
...and as far as showing events for the monitor, I wanted to clarify that unlike v1, you'll need to query the metrics endpoint for the events since Salus won't be doing any retention of events per-resource/monitor.

**Comment by itzg** [comment]
Do you mind updating the screenshot?

**Comment by FarajiA** [comment]
Yup. Here's the latest:
monitorDetailsII

**Comment by FarajiA** [comment]
Yup, here's the latest:
monitorDetailsII

**Comment by itzg** [comment]
Thanks, that aligns much better with the v2 domain model.

**Comment by FarajiA** [comment]
Latest:

monitorDetailsII

**Pull request merged**
