### PR TITLE
Default graphs mnrva 165

### PR DESCRIPTION
**Pull request by FarajiA**
## JIRA:
See ticket here - https://jira.rax.io/browse/MNRVA-165

 ## Description:
- Add flow for default graphs to populate upon loading `/visualize` route
- Update Hedwig package to 1.1.3

 ## Testing:
When navigating to visualize view with no query params a set of params will populate in URL

 ## Screenshots:
defaultGraphs

### CODE REVIEW

**Review by pras7430 — COMMENTED** [review]
the only default is working, dropdown is not selectable

**Comment by lovedeep92** [comment]
Yes @FarajiA , only default is working!
when you select metric group, you cannot select tags from tag dropdown!

**Comment by FarajiA** [comment]
Updated the dropdown logic. Items are no longer being cleared from the dropdowns.

**Review by pras7430 — APPROVED** [review]
Looks good to me!!

**Review by lovedeep92 — APPROVED** [review]

**Pull request merged**
