### PR TITLE
Adding testacses of MNRVA-507

### PR DESCRIPTION
**Pull request by RiaRenold**
## JIRA:
See ticket here - https://jira.rax.io/browse/MNRVA-507

 ## Description:
      update the dynamic plugin data of any monitor using the dynamic form component.
 ## Testing:
    npm run test:e2e
 ## Screenshots:
(if applicable)

### CODE REVIEW

**Comment by FarajiA** [comment]
@pras7430 I think you guys were working on this one day when I dropped into your Zoom session. I've attempted to keep the Chromedriver version stable at here https://github.com/racker/Minerva/blob/master/package.json#L26

Somewhere test or build process the Chromedriver got bumped up to 85 based on my error from the screenshot above.
I think I may have to specify the chromedriver version here as well
https://github.com/racker/Minerva/blob/master/Dockerfile#L85

**Comment by pras7430** [comment]
> @pras7430 I think you guys were working on this one day when I dropped into your Zoom session. I've attempted to keep the Chromedriver version stable at here https://github.com/racker/Minerva/blob/master/package.json#L26
> 
> Somewhere test or build process the Chromedriver got bumped up to 85 based on my error from the screenshot above.
> I think I may have to specify the chromedriver version here as well
> https://github.com/racker/Minerva/blob/master/Dockerfile#L85

**Comment by pras7430** [comment]
> > @pras7430 I think you guys were working on this one day when I dropped into your Zoom session. I've attempted to keep the Chromedriver version stable at here https://github.com/racker/Minerva/blob/master/package.json#L26
> > Somewhere test or build process the Chromedriver got bumped up to 85 based on my error from the screenshot above.
> > I think I may have to specify the chromedriver version here as well
> > https://github.com/racker/Minerva/blob/master/Dockerfile#L85

@FarajiA, i think it is an automatic update, As I have not made any changes in my system still I am able to run with Web-driver 85

**Comment by pras7430** [comment]
> @pras7430 I think you guys were working on this one day when I dropped into your Zoom session. I've attempted to keep the Chromedriver version stable at here https://github.com/racker/Minerva/blob/master/package.json#L26
> 
> Somewhere test or build process the Chromedriver got bumped up to 85 based on my error from the screenshot above.
> I think I may have to specify the chromedriver version here as well
> https://github.com/racker/Minerva/blob/master/Dockerfile#L85

Screenshot 2020-09-01 at 2 32 52 PM
you can see it is updated by today at my end.

**Pull request merged**
